### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by floriansigma6** [tobi08151405/open-artnet-visualizer#1]
Dear Tobi,
Look like a great tool. I'm trying to make it work but it seems that a file: /lamps_file.csv

**Comment by floriansigma6** [comment]
Ok I got it, you need to use the create_lampes.py firste.
Maybe add this step in the read me file.

**Comment by tobi08151405** [comment]
Just edited the readme, glad you figured it out yourself. If you have any other questions write me an email, or open an issue.
